// vue-app/src/molecules/NavbarMenu.vue
<template>
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <router-link class="nav-link" to="/kanban">Kanban</router-link>
    </li>
    <li class="nav-item">
      <router-link class="nav-link" to="/atomic">Atomic</router-link>
    </li>
  </ul>
</template>

<script>
export default {
  name: 'NavbarMenu',
};
</script>

// react-app/src/molecules/navbar-menu/index.js
import React from 'react';
import { Link } from 'react-router-dom';

export default function NavbarMenu() {
  return (
    <ul className="navbar-nav mr-auto">
      <li className="nav-item">
        <Link className="nav-link" to="/kanban">Kanban</Link>
      </li>
      <li className="nav-item">
        <Link className="nav-link" to="/atomic">Atomic</Link>
      </li>
    </ul>
  );
}
