// react-app/src/organisms/header/index.js
import React from 'react';
import { Link } from 'react-router-dom';

import NavbarMenu from '../../molecules/navbar-menu';
import KeyordSearch from '../../molecules/keyword-search';

export default function Header() {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <Link className="navbar-brand" to="/">DevTech</Link>

      <NavbarMenu />
      <KeyordSearch />
    </nav>
  );
}

// vue-app/src/organisms/Header.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <router-link to="/" class="navbar-brand">DevTech</router-link>

    <NavbarMenu />
    <KeywordSearch />
  </nav>
</template>

<script>
import NavbarMenu from '../molecules/NavbarMenu.vue';
import KeywordSearch from '../molecules/KeywordSearch.vue';

export default {
  name: 'Header',
  components: { NavbarMenu, KeywordSearch },
};
</script>
